### ISSUE TITLE
Doesn't work in 2.4.*

### ISSUE THREAD

**Issue by luketarplin** [egulias/ListenersDebugCommandBundle#16]
This doesn't work for 2.4.\* I just get an empty table output. Looking at the ContainerDebugCommand Class that the ListenersCommand uses I can see there are differences between 2.3.\* and 2.4.*. The method resolveServiceDefinition() which is called on line 177 & 265 is not found in the parent ContainerDebugCommand Class.

![missing-data-2_4_0](https://f.cloud.github.com/assets/3646792/1800396/2e106c9a-6bc4-11e3-9b63-b308296b5e5a.png)

**Comment by egulias** [comment]
Hi @luketarplin , thanks for the report & debug.
Have you tried updating to 1.7.0 (see the tag https://github.com/egulias/ListenersDebugCommandBundle/releases/tag/1.7.0) ? 
Please let me know if after updating everything goes fine.

**Comment by luketarplin** [comment]
Hi @egulias 1.7.0 worked fine thanks :)
