### ISSUE TITLE
Rename the command to container:listeners-debug

### ISSUE THREAD

**Issue by egulias** [egulias/ListenersDebugCommandBundle#24]
The discussion was opened in https://github.com/egulias/ListenersDebug/issues/3 by @piotrminkina

It is now moved here since is an issue with the Symfony integration, not the lib.

The name change is in order to allow short names command and to avoid collisions with `container:debug`

@lolautruche would be ok for eZ Publish?

**Comment by lolautruche** [comment]
Hi @egulias 
Should be fine, yes. Thanks for asking :)

**Comment by ghost** [comment]
i think this can be closed now? It was part of 3.0.0

**Comment by egulias** [comment]
True, thanks!
