### ISSUE TITLE
Symfony 2 (2.5) console exception by notice executing app/console container:debug:listeners

### ISSUE THREAD

**Issue by felixcarpena** [egulias/ListenersDebugCommandBundle#28]
[Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Undefined index: method in /var/www/html/beauty/vendor/egulias/listeners-debug-command-bundle/Listener/ListenerFetcher.php  
   line 81                                                  

The notice is thrown in this case (not has method):
array (1) 
 · [tag]: array (1) 
 ·  · [0]: array (3) 
 ·  ·  · [connection]: string (7) "default"
 ·  ·  · [event]: string (18) "postGenerateSchema"
 ·  ·  · [lazy]: int 1

This events belong to: http://www.doctrine-project.org/api/orm/2.4/class-Doctrine.ORM.Tools.ToolEvents.html

The symptom has a trivial solution xD: (isset($listener['method']) ? $listener['method'] : null ) 

Thanks!

**Comment by egulias** [comment]
Hi @felixcarpena !
Thanks for reporting!
I'd love a PR or a failing test ;-), if you don't have the time I'd tackle on this as soon as I have time.

**Comment by felixcarpena** [comment]
Of course! the next weekend i will have some time. I try to have a PR for then.
Thanks!

**Comment by egulias** [comment]
@felixcarpena great!
But be aware that the PR should go to the lib :)

**Comment by egulias** [comment]
Closed per PR #29
