### ISSUE TITLE
1.4.0 not in Packagist

### ISSUE THREAD

**Issue by lolautruche** [egulias/ListenersDebugCommandBundle#6]
Hello

For some reason, your tag `1.4.0` doesn't appear in Packagist. As a result, we can't require `1.4.*`.
Can you please check this ?

Thanks !

**Comment by egulias** [comment]
Thanks for the report. 
For some reason tag 1.4.0 wasn't registered. I took the chance to update the bundle description and created tag 1.4.1 . Now exists in packagist so you can require it.

**Comment by lolautruche** [comment]
Thanks!
