### ISSUE TITLE
Add priority and ordering to --event filter

### ISSUE THREAD

**Issue by egulias** [egulias/ListenersDebugCommandBundle#7]
As suggested by @lolautruche would be iteresting to have priority displayed when suing the --event filter and allow ASC and DESC ordering.

**Comment by egulias** [comment]
@lolautruche would be there any problem if we require sf2.3? TableHelper for the output simplifies a lot. Ex publish is now on sf2.3, right?

**Comment by lolautruche** [comment]
@egulias I'm fine with this, but for 1.5+ of course :smiley:

**Comment by egulias** [comment]
Done. Is now on tag 1.6.0

**Comment by lolautruche** [comment]
Yeah ! Thanks !
