### ISSUE TITLE
DataCollector for the web toolbar

### ISSUE THREAD

**Issue by kingcrunch** [egulias/ListenersDebugCommandBundle#8]
That would be nice :smile:

**Comment by egulias** [comment]
What kind of extra data are you thinking of, besides the current one being displayed in the toolbar?

**Comment by egulias** [comment]
ping @KingCrunch

**Comment by kingcrunch** [comment]
@egulias Sorry

I was talking about the Symfony2 toolbar. I am unsure, if this bundle provide the data it shows on the CLI in the toolbar too, but I hadn't time to look at yet, but I think it doesn't. Does it?

**Comment by egulias** [comment]
No, it doesn't. But because the toolbar already shows events dispatched, listeners called and not called, listeners priority and some more data. So I just wanted to know which data you miss there :)

Let me know when you found it.

**Comment by egulias** [comment]
ping @KingCrunch , do you miss any data shown in the command on the debug toolbar?

**Comment by egulias** [comment]
ping @KingCrunch , I'll close the issue this friday. I need your feedback, thanks.

**Comment by kingcrunch** [comment]
Because of me you can close it. If I'll find something, I'll come back with a PR.

**Comment by egulias** [comment]
Great, thanks!
